# This workflow will do a clean installation of a mongodb server and node dependencies, cache/restore them, and run tests across your version of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: main-ci
on:
  pull_request:
    branches: [ main ]
jobs:
  vm-job:
      runs-on: ubuntu-latest
      
      # init mongodb 
      services:
        mongodb:
          image: mongo
          options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
          ports:
          # will assign a random free host port
          - 27017/tcp
      
      # dictate node versions to test
      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      
      # jobs steps
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test
        env:
          # use localhost for the host here because we are running the job on the VM.
          # If we were running the job on in a container this would be mongodb
          MONGODB_TEST_URI: mongodb://0.0.0.0:${{ job.services.mongodb.ports[27017] }}/wz-mate-test # get randomly assigned published port
